### ISSUE TITLE
$ = require("jquery")(jsdom.jsdom().defaultView), error

### ISSUE THREAD

**Issue by ghost** [Royalgamer06/steam-free-apps#4]
I am getting this error when I try to run run.bat file.
C:\Users\Nikola Perovic\Desktop\steam-free-packages-master\main.js:5
```
$ = require("jquery")(jsdom.jsdom().defaultView),
                            ^

TypeError: jsdom.jsdom is not a function
    at Object.<anonymous> (C:\Users\Nikola Perovic\Desktop\steam-free-packages-master\main.js:5:29)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
Press any key to continue . . .
```

**Comment by tekanoma** [comment]
npm install jsdom@9.12.0 got me past this

**Comment by ghost** [comment]
Thanks @tekanoma . That worked.

**Comment by YeAhxxx** [comment]
You should close the issue if its resolved :)
